sudo: required

if: branch =~ /^(master|release-\d\d.\d)$/ AND type IN (push, cron, api)

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 173.14.28.193
      REPOSITORY: buster
      PKGTOOLS_COMMIT: origin/${TRAVIS_BRANCH}
      UPLOAD: scp
      PRIVILEGED: true
    - secure: "JRLkp8KMK7Eu4+VnnIPHN1AdGHSAWn6GI+6AJx1e7Vi92cdU4RVShPyISlIDyqFzV2Q6YGbpBWJhn7EP/kDM4qD9mhrh6lkcd+UbY6xuRmPXXiiwKzxvL3mvZBrVLo8boNB2xQKthSdUHgYY5cVxMy/Htn6rogdzds3qt19tWoLDVFQKJ/IyRS6bba4p9+F06B3Mymla1Qm+oTL0P9she9OphpyDWy/YtLcss4V+HLSgi/9yDL/OVo7g75ckAQI+uNl+BNb8VFO2EKhYXcHL7cZ+noUIL+vDpBHP2502H8kihNz3s3MXIYJ8RGv77sYJuvG9tP4+6KE9k1y36TLYH5FRJcQrWxmq14iwP3YLuRLzlA6cn9yoEIGnPxhDnZS7l32jlCb93xqAntCZzUtZyoYpxDBrQuTgW8awrGkFTfbcN8vQptc21Iw6cj6HVPmW5kjykk77lXK1pMx1g9bEHcVBKL9Yib0EYJMZI3b5YeSdMwW6+XiLUlothIkPuYCcp/Axkk7iMJBo3sYsAOyyRCGDmsu+Uw0dMaS8FpGmpiBg8uUulPFnIsyfREo24r3e7afh5Kv0Ppbj7SmiGOUv7K7QIoyZ2dvv0YIfOQ+eyUfFCiRo88aViVJiABiDaa5mBljW3yJ3I5RrD5v8Rf/uhZ+L4yObdvnoYKUN+hv65+A="
    - secure: "GEl8U8nsEgDkfJtw/TMLo2nMk0f0L8f5iEk1dXmdZ3CJbgtONkvavOkmgg89YPOuwTBjIZBVmpSC7B4PoHMvYEGuP0miM6y/EQ6Ugiq9azY5IRTX7yT0urv+Z1oS9+JdW9HmJ0Sfb5CUUjURW/pDCyzH3pxIi+ss/GTEjpM1zyjvJXLBybURYSa8DF7qc8JYYasYy+61+mPkLf+FIn6jzSmwyi6nxPdG3V2SuhVgk8OpS8MAA7a5d2rPabWPED9cIp1NWLEF6nqYBVL2fpSPqCDaxSJrzHIqEDLZXE0CFBd7K05oSP+WWVCP4YcshUr54QE0RifAHxF8wqhLsq9aNFWD34mSbRpk+/5lSZVGqxvSs8Szr/AgHYqtEwpCLqedCImPMowdmH33d1FICMltiem3WOo1AQ20mIVfHDW4pF9DB4F3BthLMHcO516DOtw4LYT+6Z8EtEYum5X0cnmfzKL3gtsmDvOC3SMtSF2I01zq3NgR2OB+2CUiFz3VUp0Ky4LiguJfNrwhC0bPzlJ0nfk+yYa3xxjJ787JlDzPJpUqcNzN4o4NtmkZVZS026ng8ppCWvHqnCYg8C/pud98PeigjONtnax8Sgded0utblBNR4zqw8xgZkjYltyCjE9wtdMpgadwsS4cJSa9jAn0bj8n7vSs6AOw02yqv8g1zE4="
  jobs:
    - ARCHITECTURE: amd64

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-cloud
- openssl aes-256-cbc -K $encrypted_c3a944c0ebdd_key -iv $encrypted_c3a944c0ebdd_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

jobs:
  include:
    - stage: build qcow2
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make -f Makefile.ngfw qcow2/untangle-image qcow2/untangle-push"

    - stage: build ova
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make -f Makefile.ngfw ova/untangle-image ova/untangle-push"

    - stage: build ec2/byol
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make -f Makefile.ngfw  ec2/byol/untangle-image ec2/byol/untangle-push"
      if: type = api

    - stage: build ec2/payg
      script:
        - docker-compose -f docker-compose.build.yml run pkgtools
        - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make -f Makefile.ngfw  ec2/payg/untangle-image ec2/byol/untangle-push"
      if: type = api

notifications:
  email: false
  slack:
    rooms:
      secure: etYXoWsq2ePvfPjomw7wmsCP6woeJp461dD5Yo5brSdTL0exTTNh+atSnX1MgqbQytsYy4PwQoAQb8jBzn+FPuLjdts/aKIClU4uTt0ZKs4gfAC368Wv//6WjxSjkFjeHtSht/ALcergEwCy3HsIgOai41egzy/YIDVSkgBxUrPaH6zcI0mTwhW6Ss7C91FJtndy8REvhKn5TNLRndXSLMF/EdVeFxPzA5yVM4MCcFbzUlbscs+C8/J3hD2no/38opSwqojBqaPQBFiI5LHCGLJqfWcIhCUA6YTVi12WpYLWlOutX2RpJpVU8N9kvnBpvhuoypgkzLNtJ8CZCwoBRdbUS78EPUmbCRiQxHquCkKjKUemSMrL4FqTrJL/NejQHz1c86aHJvgL/nql+zticD0RueFDVYZsFxvN8KCd/C28lkcE0jaDQUm7z01jDjWgqT/nMyqokI8MFydQGtSoRvp6GMNrJPlQg0XoNZkjHwyhPVTAf77Nyq2aht6tkGVcWQA7SVMAXlT8ZptJ4nvEq5EU0KhrXc/z9XeipmPORGOq+Yn775xlLR64ERBNhrUOvu+yPRkmYKUKkCzYgOQuih+KwPQZe3NGy+XlxXq4Io/+yDgpmophkYm1YsMjbpohw7m+uiNSlLnMFM92Sse+qOy4x1Fkb/D8jbnqaX+7eV4=
    on_success: change
    on_failure: always
