dist: focal

if: branch =~ /^(master|((ngfw|waf)-)?release-\d+.\d)$/ AND type IN (push, cron, api) AND tag IS blank

git:
  depth: false

services:
- docker

env:
  global:
    # DOCKER_PASSWORD
    - secure: "h2VLkq6zGpVWlvS0bQgcvVQjYmq+xgcweuihFiaFmpvzarASPCzW/T8WlCril90BMP8WKhG9N5zFGCe1VBSuFwzUxpalqQL7w9vXFepqIb67MjXmGDVXsYmXOqJfB7g2J9E1x/lfZrOR+OmqAZeV6xT6LbMIXbS60D/8ks1waJKvLWNG64MUa74JKZAkHeEUle+medhwilR3Raz4G7Wl6RhAvjwzDTu42/Ac5WLWUZHCGbZZp2jwJPOoWvPwGk9biwQw7oyl5M9fKSB2iodbvQbKrXGR+AS9OvAl/Jl/xAfZ7Rz823RriNbb3MpHLTjHwkuD8rXfgdga7hWi4Wh14bTMKywfc3VO1W8RVsgKvX2+xkFfuWkanwkFxHyMnL77+V1E101p7gpdhY6yuLzSi9UWGYM60QoVNg6IIuWo6kvEfB5V+rFwEmVTSQDZc0s5vfG/WBtye1QzvWcJbEWxYS6TchkJ+f/ZMk2V0+cugmO8t3W7AfZA+JGKr9pOMhhTonWCgg00r+/kgYZNa9dNAUNrLaY3gPfT+xjWx9bjdIPUBaqKjApLGCWHvLpgWZGFndZcAFJQRvdyHTvkirU9sftoR+rq528IETdtnhMZ+pBOB9yrFCduXZL2gsFXa6XHFWbh+ijkrDzJ+pdrPjy69oMRJgSMg4S9RH6oQs5bz1g="
    - DOCKER_USERNAME: untangleengineering
      SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 52.2.228.218
      REPOSITORY: bullseye
      PKGTOOLS_COMMIT: origin/${TRAVIS_BRANCH}
      UPLOAD: scp
      PRIVILEGED: true
    # AWS_ACCESS_KEY_ID
    - secure: "bDKKD5hSzAJvydh9/irwoDT/DyAYvjClMTyphCgeJpwLgz43GADR9ArJA8JX6YN6VMhAMOUhcuMo1u3bDfXkYXUKhm91rcHyWJc9aErkMTrFaDWpXKJiXdZhOYT2YNiRVjdm5zxZXLnkjyCR0mL6v/2a1JZm+3vBC89l0HtA+gcRLQ+BIfNa50+qw9Vgn3P0tsJnfl4fqCrnb0AykauV0gXRpLIrBF8/9Sr5oDtoXlXHZ9aPrt4Ibt7NHTS1crrzDkFCltSsxtuqvyRjY1clLVprPGSA3DXwFU+Uf3SjVmmRVzo3GclPa661R59rTvWFmXQXm5aXWINclfolHKaJU7/N7alE0IIP6jBBDknvBSFugAT/c6FZFyD9MYJikP5XGjs7IRF73PZb74R3S91v0pXj6LsgYARCGKGDPtgghxBITx9j0B9pm5AaR9mFI+dx3Sn3cYRQ509vihsO0Kg7QL+p+EvDhLyNoSb/eHlPUuNvIGab5zvtvNNgxoD8yEbzp3JazKS0dqccGorlDrpOQyHgoBA6BbrMXVc+/uZZf5XKdFQ/5tdYSKUpyzKXgbMF5uBsTgL4413xnm7da+pHzQ9BiiqubuRmZxsqs+MnYqUJgzQptB4dWyC5p7Yp3qlyPJ7E9mrgDmDlbYApPzTciisap1fhHn1JrK+qqjydF7Q="
    # AWS_SECRET_ACCESS_KEY
    - secure: "AZ/Hhjnc+qClOmDxL8cR2J4yUMvzJfm5ZtSCytxRPl7/gFKI/3oA/h1bHOuywIXhtRAzLerD685vvXGzSSXCotvtI/V9/SFo3UDJ7kEQrj4P2KDFPZRyUrGxUtNG8ZzcU9CPKlROkABBoAaCxLnI+A929wFDD4dXTM2lWtlilbE2v3Xf5mVrB5LJJDLFxdn5y3kH8W6vUgzv+ua7+9sBRlKumo0Mh8bdqTIhz8TQV8EzfCxRVKSf1sxPbRX/s/LY8eCJN93WtaHq69qX4JlnNlT4YYAj6BMneUeutQuyfrbnikOlWl8ByxGgnJy9c1ovIer7wjzMbazxOIAFZhV4adAPDxtQ5tBdd+7KFNhCISsmkNP8Ycx3TAnkCHmt2DA0SedQW5mkAHuKZDggo4iX/JiLrw0WWQpH7veKVsaVs9vSOxyubXOSY0N2ZJPNCkdEkWKd7Avq/z+DixSKMi+8b9GY2f+1x0wKqwHlv2lPwYdO8449kuSPQjOd5DPcO+pexFjYokLoBK9t7ZqYp+7lHB7opvVuXAwGtY5M+kkf24/c2dGtYvnKuB4sIKBBQV0QxhLxjiOTZLSXiCmYZmBnjmsMMnFbGThGa3c6xu7eYaqlJXGxG5BOD7Jn9oJnr6VhE37TrdKYtFyJf4nYUOzVviy+UHjcuhpOJAb5IVwiHWw="
    # AZURE_AUTH_SECRET
    - secure: "aUtzZHpeQX37MDRNrqpswSk4alXjICTOP1AE95A2t97ebkijm1tHEigFxYz8sMXeu9xN7It3reGimBbX2n6YlOOm8G4N05yHuayIDzFDKjCBQLc3MoFmUtDhK2I3x/KIjdX5mBrphbL6ULG7PFaBCAVBN+i/KLs8L4pOR8Phx5nW1DfwJnRS53kp4EyWxQ8ZDzvdGE8i/MA/6VxVrbmcRDxL0RKk/IRbeATCmbAU0/70L6Lq5EXRL3NJcWw+175o8N4vLTJ/wjoObWFJvdFQ1VslwK/ukJQx2NXy+tJ0sWfdo6asQGYIyiPy6Zi9Viq6hTGDOnAm/z3FY9bpzUE3TmPIn33bStW9RAw9ixfteU4bgxdbbRE2H8acTwyFc4Ge8YhCqG+SOIWl8dQ6CABibXK2AMjpTQRsMTpfC2EIJeX9CCCq7D5OpNEZuJhK0axKL0q9kmIc4FsNU4oiupPgQNdZcJ0NyNvwAtKzfjGk5K2NB1JTQF/BZGpPaoi+nFOfVyPMJvHyLMQrBDBpVfrTYfHGATQPUyhzPVWwoQJppb/vDLBZAuTcsI15wcCpV1Tk/XDkKMiTd1Jbfk03odOLA0ip6D1t1sK6ikwDsZz6t3wcnzBAQI/taQZZDZBn4HluWb6cDhVvuLXbP4K4eofx/FF8mIEQAeGKSp/hFh/Xs3A="
    # AZURE_IMAGE_SUBSCRIPTION_ID
    - secure: "iZ6lQequHxODnzqiKluOefsvE+QxKqx9taBvPoViXr8xhUYQV+SRdM5izDn8j9esXIXWOtXWtXsG0220pMpyIWFdthSTRboYp+hUQb5IVI5Z4JAI3EughyG1QGVoJxYTk0yeFJyQ8Pp8O2knAy1+o3p7ULzGne6eGQTy/RDaaWB+YbmuFb0OQjc9WA8SC3pZadpYTiITrHSmz7PIRVHbNYprAC24kfqE6AbnnlwhnPmAXGZZYwQu4D9k5BbVNE4yz/6yQqHZJmtVINbevz8RBKIbWIg/QBFc+pXQz+F84j3CYllITDtsydocg4V96xiwktN6XlZ6JCw6fHW0I2Yf5alhJJZzZSzxrSZ8S0tOZiSC2IcM3dZeoUHRjgyZ4GoHZN4GERTfrfMp7kmZmu9Kp+e6Ok8CIvhuBZInSvlAVBFGUzb8jMVQpGlFSrQ1mapit4ci66hh8lrKphXMxHWoHnUufp+vK+8VZCMwfODTOO++2nykGEBlO3mla7qT+VFlzeX7SzfgZixNk6jgdRLEPTFvvvRxAjToDR6N0FUC/kgrkxLmkvJHKYu6oBF8QVZnFHoRpW+GnA/yS6WSgN4FLm/F8zQx9Q0GcohYYPwD7O70jPmjuOYCLwW1y/JfiWd0rR4CDKtBja8zMPbz4a8jeiucuV987H0YXHnQkrXAluM="
    # AZURE_STORAGE_SUBSCRIPTION_ID
    - secure: "gtDfuuZpTJSWayRfJwvP9GM+6IBlv3bkY0sVJGfnOJJZylasLZphY1kIOkRXiRqitsap543RmHI8qXovcVRy5nkZ1WqP/y0+8VBCuiDit7OU5x6iUc4sldJaCj9ePCYdhJozpam6hyypp/A/7MyilffiWAh1FbgfntwXlcJ4SsTypuagiCtjqBGJ56tKQNmGRqdNJxWkZhiP+D9X/MCkwuKJOUOyQNzW8jhqxNc+jhjty0DwJ4q+XIuf4Cpau/cnffl0Epj0OOIS3odUJ8DtbB3iMM0RWCjtD0U3u2k8kmwD8neL81Sc58XedPy3AaN9VMNrN1cxdBAzRhAkJ9uTt0jemDfq5kWB0zpvmqX1waywbNWG6TvKYJ26zwBxt6UjuWIRjq5hLamRLbbqPmvns5GLIR+oG6PnTIi3IMVhqwI0Bz2N6XYFtyhs6kVtpsYhFsSM5qAcKOw1G44Yq9y7giSnj/Wg27c0FIQC+mO9ZwK1RzaDAhl6Hl1YK6ikjiqzLIUMQ4fei0w4BwyjOtEyHAhX2F241/zRJAYXNbjsHydv0L5CY6efOS5nLVWBtg2KvVU7qyIpUm7Gyy8Yf5wBlWl9I4xDov1Hy8W5an+OPzKqIzF1+HoOR4iGUad7k/iBrL+i8aFu5We3zswGci/XPL8ssXy6bh23AVh77ESC1EA="
  jobs:
    - ARCHITECTURE: amd64
      TYPE: qcow2
      VENDOR: untangle
    - ARCHITECTURE: amd64
      TYPE: ec2/byol
      VENDOR: untangle
    - ARCHITECTURE: amd64
      TYPE: ec2/payg
      VENDOR: untangle
    - ARCHITECTURE: amd64
      TYPE: azure/byol
      VENDOR: untangle
    - ARCHITECTURE: amd64
      TYPE: azure/payg
      VENDOR: untangle
    - ARCHITECTURE: arm64
      TYPE: qcow2
      VENDOR: untangle
    - ARCHITECTURE: arm64
      TYPE: ec2/byol
      VENDOR: untangle
    - ARCHITECTURE: arm64
      TYPE: ec2/payg
      VENDOR: untangle

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull untangleinc/ngfw:${REPOSITORY}-cloud
- openssl aes-256-cbc -K $encrypted_c3a944c0ebdd_key -iv $encrypted_c3a944c0ebdd_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
  - sudo apt update
  - sudo apt install -y qemu-user-static binfmt-support
  - docker-compose -f docker-compose.build.yml run pkgtools
  - docker-compose -f docker-compose.build.yml run build bash -c "../ngfw_pkgtools/build.sh setup-only && make -f Makefile.ngfw ${TYPE}/${VENDOR}-image ${TYPE}/${VENDOR}-push"
if: NOT (env(REPOSITORY) = buster AND branch = master) AND (type = api OR NOT env(TYPE) =~ /(ec2|azure)/)

notifications:
  email: false
  slack:
    rooms:
      secure: etYXoWsq2ePvfPjomw7wmsCP6woeJp461dD5Yo5brSdTL0exTTNh+atSnX1MgqbQytsYy4PwQoAQb8jBzn+FPuLjdts/aKIClU4uTt0ZKs4gfAC368Wv//6WjxSjkFjeHtSht/ALcergEwCy3HsIgOai41egzy/YIDVSkgBxUrPaH6zcI0mTwhW6Ss7C91FJtndy8REvhKn5TNLRndXSLMF/EdVeFxPzA5yVM4MCcFbzUlbscs+C8/J3hD2no/38opSwqojBqaPQBFiI5LHCGLJqfWcIhCUA6YTVi12WpYLWlOutX2RpJpVU8N9kvnBpvhuoypgkzLNtJ8CZCwoBRdbUS78EPUmbCRiQxHquCkKjKUemSMrL4FqTrJL/NejQHz1c86aHJvgL/nql+zticD0RueFDVYZsFxvN8KCd/C28lkcE0jaDQUm7z01jDjWgqT/nMyqokI8MFydQGtSoRvp6GMNrJPlQg0XoNZkjHwyhPVTAf77Nyq2aht6tkGVcWQA7SVMAXlT8ZptJ4nvEq5EU0KhrXc/z9XeipmPORGOq+Yn775xlLR64ERBNhrUOvu+yPRkmYKUKkCzYgOQuih+KwPQZe3NGy+XlxXq4Io/+yDgpmophkYm1YsMjbpohw7m+uiNSlLnMFM92Sse+qOy4x1Fkb/D8jbnqaX+7eV4=
    on_success: change
    on_failure: always
